#dist: trusty
language: php
env:
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
#  - hhvm
  - nightly
before_script:
  - phpunit --version
  - composer require phpunit/phpunit
  - find .
  - ./vendor/bin/phpunit --version
script:
  - ./vendor/bin/phpunit test/
